/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarreirasRouteImport } from './routes/carreiras'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CarreiraCareerIdRouteImport } from './routes/carreira.$careerId'
import { Route as CarreirasNovaRouteImport } from './routes/carreiras.nova'
import { Route as CarreiraCareerIdIndexRouteImport } from './routes/carreira.$careerId.index'
import { Route as CarreiraCareerIdClimaRouteImport } from './routes/carreira.$careerId.clima'
import { Route as CarreiraCareerIdDiretoriaRouteImport } from './routes/carreira.$careerId.diretoria'
import { Route as CarreiraCareerIdElencoRouteImport } from './routes/carreira.$careerId.elenco'
import { Route as CarreiraCareerIdEscalacaoRouteImport } from './routes/carreira.$careerId.escalacao'
import { Route as CarreiraCareerIdEstatisticasRouteImport } from './routes/carreira.$careerId.estatisticas'
import { Route as CarreiraCareerIdFinancasRouteImport } from './routes/carreira.$careerId.financas'
import { Route as CarreiraCareerIdJogoRouteImport } from './routes/carreira.$careerId.jogo'
import { Route as CarreiraCareerIdMedicoRouteImport } from './routes/carreira.$careerId.medico'
import { Route as CarreiraCareerIdMercadoRouteImport } from './routes/carreira.$careerId.mercado'
import { Route as CarreiraCareerIdNoticiasRouteImport } from './routes/carreira.$careerId.noticias'
import { Route as CarreiraCareerIdPreparacaoRouteImport } from './routes/carreira.$careerId.preparacao'
import { Route as CarreiraCareerIdPropostasRouteImport } from './routes/carreira.$careerId.propostas'
import { Route as CarreiraCareerIdSocialRouteImport } from './routes/carreira.$careerId.social'
import { Route as CarreiraCareerIdTabelaRouteImport } from './routes/carreira.$careerId.tabela'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarreirasRoute = CarreirasRouteImport.update({
  id: '/carreiras',
  path: '/carreiras',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CarreiraCareerIdRoute = CarreiraCareerIdRouteImport.update({
  id: '/carreira/$careerId',
  path: '/carreira/$careerId',
  getParentRoute: () => rootRouteImport,
} as any)
const CarreirasNovaRoute = CarreirasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => CarreirasRoute,
} as any)
const CarreiraCareerIdIndexRoute = CarreiraCareerIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarreiraCareerIdRoute,
} as any)
const CarreiraCareerIdClimaRoute = CarreiraCareerIdClimaRouteImport.update({
  id: '/clima',
  path: '/clima',
  getParentRoute: () => CarreiraCareerIdRoute,
} as any)
const CarreiraCareerIdDiretoriaRoute =
  CarreiraCareerIdDiretoriaRouteImport.update({
    id: '/diretoria',
    path: '/diretoria',
    getParentRoute: () => CarreiraCareerIdRoute,
  } as any)
const CarreiraCareerIdElencoRoute = CarreiraCareerIdElencoRouteImport.update({
  id: '/elenco',
  path: '/elenco',
  getParentRoute: () => CarreiraCareerIdRoute,
} as any)
const CarreiraCareerIdEscalacaoRoute =
  CarreiraCareerIdEscalacaoRouteImport.update({
    id: '/escalacao',
    path: '/escalacao',
    getParentRoute: () => CarreiraCareerIdRoute,
  } as any)
const CarreiraCareerIdEstatisticasRoute =
  CarreiraCareerIdEstatisticasRouteImport.update({
    id: '/estatisticas',
    path: '/estatisticas',
    getParentRoute: () => CarreiraCareerIdRoute,
  } as any)
const CarreiraCareerIdFinancasRoute =
  CarreiraCareerIdFinancasRouteImport.update({
    id: '/financas',
    path: '/financas',
    getParentRoute: () => CarreiraCareerIdRoute,
  } as any)
const CarreiraCareerIdJogoRoute = CarreiraCareerIdJogoRouteImport.update({
  id: '/jogo',
  path: '/jogo',
  getParentRoute: () => CarreiraCareerIdRoute,
} as any)
const CarreiraCareerIdMedicoRoute = CarreiraCareerIdMedicoRouteImport.update({
  id: '/medico',
  path: '/medico',
  getParentRoute: () => CarreiraCareerIdRoute,
} as any)
const CarreiraCareerIdMercadoRoute = CarreiraCareerIdMercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => CarreiraCareerIdRoute,
} as any)
const CarreiraCareerIdNoticiasRoute =
  CarreiraCareerIdNoticiasRouteImport.update({
    id: '/noticias',
    path: '/noticias',
    getParentRoute: () => CarreiraCareerIdRoute,
  } as any)
const CarreiraCareerIdPreparacaoRoute =
  CarreiraCareerIdPreparacaoRouteImport.update({
    id: '/preparacao',
    path: '/preparacao',
    getParentRoute: () => CarreiraCareerIdRoute,
  } as any)
const CarreiraCareerIdPropostasRoute =
  CarreiraCareerIdPropostasRouteImport.update({
    id: '/propostas',
    path: '/propostas',
    getParentRoute: () => CarreiraCareerIdRoute,
  } as any)
const CarreiraCareerIdSocialRoute = CarreiraCareerIdSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => CarreiraCareerIdRoute,
} as any)
const CarreiraCareerIdTabelaRoute = CarreiraCareerIdTabelaRouteImport.update({
  id: '/tabela',
  path: '/tabela',
  getParentRoute: () => CarreiraCareerIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carreiras': typeof CarreirasRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/carreira/$careerId': typeof CarreiraCareerIdRouteWithChildren
  '/carreiras/nova': typeof CarreirasNovaRoute
  '/carreira/$careerId/clima': typeof CarreiraCareerIdClimaRoute
  '/carreira/$careerId/diretoria': typeof CarreiraCareerIdDiretoriaRoute
  '/carreira/$careerId/elenco': typeof CarreiraCareerIdElencoRoute
  '/carreira/$careerId/escalacao': typeof CarreiraCareerIdEscalacaoRoute
  '/carreira/$careerId/estatisticas': typeof CarreiraCareerIdEstatisticasRoute
  '/carreira/$careerId/financas': typeof CarreiraCareerIdFinancasRoute
  '/carreira/$careerId/jogo': typeof CarreiraCareerIdJogoRoute
  '/carreira/$careerId/medico': typeof CarreiraCareerIdMedicoRoute
  '/carreira/$careerId/mercado': typeof CarreiraCareerIdMercadoRoute
  '/carreira/$careerId/noticias': typeof CarreiraCareerIdNoticiasRoute
  '/carreira/$careerId/preparacao': typeof CarreiraCareerIdPreparacaoRoute
  '/carreira/$careerId/propostas': typeof CarreiraCareerIdPropostasRoute
  '/carreira/$careerId/social': typeof CarreiraCareerIdSocialRoute
  '/carreira/$careerId/tabela': typeof CarreiraCareerIdTabelaRoute
  '/carreira/$careerId/': typeof CarreiraCareerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carreiras': typeof CarreirasRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/carreiras/nova': typeof CarreirasNovaRoute
  '/carreira/$careerId/clima': typeof CarreiraCareerIdClimaRoute
  '/carreira/$careerId/diretoria': typeof CarreiraCareerIdDiretoriaRoute
  '/carreira/$careerId/elenco': typeof CarreiraCareerIdElencoRoute
  '/carreira/$careerId/escalacao': typeof CarreiraCareerIdEscalacaoRoute
  '/carreira/$careerId/estatisticas': typeof CarreiraCareerIdEstatisticasRoute
  '/carreira/$careerId/financas': typeof CarreiraCareerIdFinancasRoute
  '/carreira/$careerId/jogo': typeof CarreiraCareerIdJogoRoute
  '/carreira/$careerId/medico': typeof CarreiraCareerIdMedicoRoute
  '/carreira/$careerId/mercado': typeof CarreiraCareerIdMercadoRoute
  '/carreira/$careerId/noticias': typeof CarreiraCareerIdNoticiasRoute
  '/carreira/$careerId/preparacao': typeof CarreiraCareerIdPreparacaoRoute
  '/carreira/$careerId/propostas': typeof CarreiraCareerIdPropostasRoute
  '/carreira/$careerId/social': typeof CarreiraCareerIdSocialRoute
  '/carreira/$careerId/tabela': typeof CarreiraCareerIdTabelaRoute
  '/carreira/$careerId': typeof CarreiraCareerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carreiras': typeof CarreirasRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/carreira/$careerId': typeof CarreiraCareerIdRouteWithChildren
  '/carreiras/nova': typeof CarreirasNovaRoute
  '/carreira/$careerId/clima': typeof CarreiraCareerIdClimaRoute
  '/carreira/$careerId/diretoria': typeof CarreiraCareerIdDiretoriaRoute
  '/carreira/$careerId/elenco': typeof CarreiraCareerIdElencoRoute
  '/carreira/$careerId/escalacao': typeof CarreiraCareerIdEscalacaoRoute
  '/carreira/$careerId/estatisticas': typeof CarreiraCareerIdEstatisticasRoute
  '/carreira/$careerId/financas': typeof CarreiraCareerIdFinancasRoute
  '/carreira/$careerId/jogo': typeof CarreiraCareerIdJogoRoute
  '/carreira/$careerId/medico': typeof CarreiraCareerIdMedicoRoute
  '/carreira/$careerId/mercado': typeof CarreiraCareerIdMercadoRoute
  '/carreira/$careerId/noticias': typeof CarreiraCareerIdNoticiasRoute
  '/carreira/$careerId/preparacao': typeof CarreiraCareerIdPreparacaoRoute
  '/carreira/$careerId/propostas': typeof CarreiraCareerIdPropostasRoute
  '/carreira/$careerId/social': typeof CarreiraCareerIdSocialRoute
  '/carreira/$careerId/tabela': typeof CarreiraCareerIdTabelaRoute
  '/carreira/$careerId/': typeof CarreiraCareerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carreiras'
    | '/auth/callback'
    | '/carreira/$careerId'
    | '/carreiras/nova'
    | '/carreira/$careerId/clima'
    | '/carreira/$careerId/diretoria'
    | '/carreira/$careerId/elenco'
    | '/carreira/$careerId/escalacao'
    | '/carreira/$careerId/estatisticas'
    | '/carreira/$careerId/financas'
    | '/carreira/$careerId/jogo'
    | '/carreira/$careerId/medico'
    | '/carreira/$careerId/mercado'
    | '/carreira/$careerId/noticias'
    | '/carreira/$careerId/preparacao'
    | '/carreira/$careerId/propostas'
    | '/carreira/$careerId/social'
    | '/carreira/$careerId/tabela'
    | '/carreira/$careerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carreiras'
    | '/auth/callback'
    | '/carreiras/nova'
    | '/carreira/$careerId/clima'
    | '/carreira/$careerId/diretoria'
    | '/carreira/$careerId/elenco'
    | '/carreira/$careerId/escalacao'
    | '/carreira/$careerId/estatisticas'
    | '/carreira/$careerId/financas'
    | '/carreira/$careerId/jogo'
    | '/carreira/$careerId/medico'
    | '/carreira/$careerId/mercado'
    | '/carreira/$careerId/noticias'
    | '/carreira/$careerId/preparacao'
    | '/carreira/$careerId/propostas'
    | '/carreira/$careerId/social'
    | '/carreira/$careerId/tabela'
    | '/carreira/$careerId'
  id:
    | '__root__'
    | '/'
    | '/carreiras'
    | '/auth/callback'
    | '/carreira/$careerId'
    | '/carreiras/nova'
    | '/carreira/$careerId/clima'
    | '/carreira/$careerId/diretoria'
    | '/carreira/$careerId/elenco'
    | '/carreira/$careerId/escalacao'
    | '/carreira/$careerId/estatisticas'
    | '/carreira/$careerId/financas'
    | '/carreira/$careerId/jogo'
    | '/carreira/$careerId/medico'
    | '/carreira/$careerId/mercado'
    | '/carreira/$careerId/noticias'
    | '/carreira/$careerId/preparacao'
    | '/carreira/$careerId/propostas'
    | '/carreira/$careerId/social'
    | '/carreira/$careerId/tabela'
    | '/carreira/$careerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarreirasRoute: typeof CarreirasRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  CarreiraCareerIdRoute: typeof CarreiraCareerIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreiras': {
      id: '/carreiras'
      path: '/carreiras'
      fullPath: '/carreiras'
      preLoaderRoute: typeof CarreirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreira/$careerId': {
      id: '/carreira/$careerId'
      path: '/carreira/$careerId'
      fullPath: '/carreira/$careerId'
      preLoaderRoute: typeof CarreiraCareerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreiras/nova': {
      id: '/carreiras/nova'
      path: '/nova'
      fullPath: '/carreiras/nova'
      preLoaderRoute: typeof CarreirasNovaRouteImport
      parentRoute: typeof CarreirasRoute
    }
    '/carreira/$careerId/': {
      id: '/carreira/$careerId/'
      path: '/'
      fullPath: '/carreira/$careerId/'
      preLoaderRoute: typeof CarreiraCareerIdIndexRouteImport
      parentRoute: typeof CarreiraCareerIdRoute
    }
    '/carreira/$careerId/clima': {
      id: '/carreira/$careerId/clima'
      path: '/clima'
      fullPath: '/carreira/$careerId/clima'
      preLoaderRoute: typeof CarreiraCareerIdClimaRouteImport
      parentRoute: typeof CarreiraCareerIdRoute
    }
    '/carreira/$careerId/diretoria': {
      id: '/carreira/$careerId/diretoria'
      path: '/diretoria'
      fullPath: '/carreira/$careerId/diretoria'
      preLoaderRoute: typeof CarreiraCareerIdDiretoriaRouteImport
      parentRoute: typeof CarreiraCareerIdRoute
    }
    '/carreira/$careerId/elenco': {
      id: '/carreira/$careerId/elenco'
      path: '/elenco'
      fullPath: '/carreira/$careerId/elenco'
      preLoaderRoute: typeof CarreiraCareerIdElencoRouteImport
      parentRoute: typeof CarreiraCareerIdRoute
    }
    '/carreira/$careerId/escalacao': {
      id: '/carreira/$careerId/escalacao'
      path: '/escalacao'
      fullPath: '/carreira/$careerId/escalacao'
      preLoaderRoute: typeof CarreiraCareerIdEscalacaoRouteImport
      parentRoute: typeof CarreiraCareerIdRoute
    }
    '/carreira/$careerId/estatisticas': {
      id: '/carreira/$careerId/estatisticas'
      path: '/estatisticas'
      fullPath: '/carreira/$careerId/estatisticas'
      preLoaderRoute: typeof CarreiraCareerIdEstatisticasRouteImport
      parentRoute: typeof CarreiraCareerIdRoute
    }
    '/carreira/$careerId/financas': {
      id: '/carreira/$careerId/financas'
      path: '/financas'
      fullPath: '/carreira/$careerId/financas'
      preLoaderRoute: typeof CarreiraCareerIdFinancasRouteImport
      parentRoute: typeof CarreiraCareerIdRoute
    }
    '/carreira/$careerId/jogo': {
      id: '/carreira/$careerId/jogo'
      path: '/jogo'
      fullPath: '/carreira/$careerId/jogo'
      preLoaderRoute: typeof CarreiraCareerIdJogoRouteImport
      parentRoute: typeof CarreiraCareerIdRoute
    }
    '/carreira/$careerId/medico': {
      id: '/carreira/$careerId/medico'
      path: '/medico'
      fullPath: '/carreira/$careerId/medico'
      preLoaderRoute: typeof CarreiraCareerIdMedicoRouteImport
      parentRoute: typeof CarreiraCareerIdRoute
    }
    '/carreira/$careerId/mercado': {
      id: '/carreira/$careerId/mercado'
      path: '/mercado'
      fullPath: '/carreira/$careerId/mercado'
      preLoaderRoute: typeof CarreiraCareerIdMercadoRouteImport
      parentRoute: typeof CarreiraCareerIdRoute
    }
    '/carreira/$careerId/noticias': {
      id: '/carreira/$careerId/noticias'
      path: '/noticias'
      fullPath: '/carreira/$careerId/noticias'
      preLoaderRoute: typeof CarreiraCareerIdNoticiasRouteImport
      parentRoute: typeof CarreiraCareerIdRoute
    }
    '/carreira/$careerId/preparacao': {
      id: '/carreira/$careerId/preparacao'
      path: '/preparacao'
      fullPath: '/carreira/$careerId/preparacao'
      preLoaderRoute: typeof CarreiraCareerIdPreparacaoRouteImport
      parentRoute: typeof CarreiraCareerIdRoute
    }
    '/carreira/$careerId/propostas': {
      id: '/carreira/$careerId/propostas'
      path: '/propostas'
      fullPath: '/carreira/$careerId/propostas'
      preLoaderRoute: typeof CarreiraCareerIdPropostasRouteImport
      parentRoute: typeof CarreiraCareerIdRoute
    }
    '/carreira/$careerId/social': {
      id: '/carreira/$careerId/social'
      path: '/social'
      fullPath: '/carreira/$careerId/social'
      preLoaderRoute: typeof CarreiraCareerIdSocialRouteImport
      parentRoute: typeof CarreiraCareerIdRoute
    }
    '/carreira/$careerId/tabela': {
      id: '/carreira/$careerId/tabela'
      path: '/tabela'
      fullPath: '/carreira/$careerId/tabela'
      preLoaderRoute: typeof CarreiraCareerIdTabelaRouteImport
      parentRoute: typeof CarreiraCareerIdRoute
    }
  }
}

interface CarreirasRouteChildren {
  CarreirasNovaRoute: typeof CarreirasNovaRoute
}

const CarreirasRouteChildren: CarreirasRouteChildren = {
  CarreirasNovaRoute: CarreirasNovaRoute,
}

const CarreirasRouteWithChildren = CarreirasRoute._addFileChildren(
  CarreirasRouteChildren,
)

interface CarreiraCareerIdRouteChildren {
  CarreiraCareerIdClimaRoute: typeof CarreiraCareerIdClimaRoute
  CarreiraCareerIdDiretoriaRoute: typeof CarreiraCareerIdDiretoriaRoute
  CarreiraCareerIdElencoRoute: typeof CarreiraCareerIdElencoRoute
  CarreiraCareerIdEscalacaoRoute: typeof CarreiraCareerIdEscalacaoRoute
  CarreiraCareerIdEstatisticasRoute: typeof CarreiraCareerIdEstatisticasRoute
  CarreiraCareerIdFinancasRoute: typeof CarreiraCareerIdFinancasRoute
  CarreiraCareerIdJogoRoute: typeof CarreiraCareerIdJogoRoute
  CarreiraCareerIdMedicoRoute: typeof CarreiraCareerIdMedicoRoute
  CarreiraCareerIdMercadoRoute: typeof CarreiraCareerIdMercadoRoute
  CarreiraCareerIdNoticiasRoute: typeof CarreiraCareerIdNoticiasRoute
  CarreiraCareerIdPreparacaoRoute: typeof CarreiraCareerIdPreparacaoRoute
  CarreiraCareerIdPropostasRoute: typeof CarreiraCareerIdPropostasRoute
  CarreiraCareerIdSocialRoute: typeof CarreiraCareerIdSocialRoute
  CarreiraCareerIdTabelaRoute: typeof CarreiraCareerIdTabelaRoute
  CarreiraCareerIdIndexRoute: typeof CarreiraCareerIdIndexRoute
}

const CarreiraCareerIdRouteChildren: CarreiraCareerIdRouteChildren = {
  CarreiraCareerIdClimaRoute: CarreiraCareerIdClimaRoute,
  CarreiraCareerIdDiretoriaRoute: CarreiraCareerIdDiretoriaRoute,
  CarreiraCareerIdElencoRoute: CarreiraCareerIdElencoRoute,
  CarreiraCareerIdEscalacaoRoute: CarreiraCareerIdEscalacaoRoute,
  CarreiraCareerIdEstatisticasRoute: CarreiraCareerIdEstatisticasRoute,
  CarreiraCareerIdFinancasRoute: CarreiraCareerIdFinancasRoute,
  CarreiraCareerIdJogoRoute: CarreiraCareerIdJogoRoute,
  CarreiraCareerIdMedicoRoute: CarreiraCareerIdMedicoRoute,
  CarreiraCareerIdMercadoRoute: CarreiraCareerIdMercadoRoute,
  CarreiraCareerIdNoticiasRoute: CarreiraCareerIdNoticiasRoute,
  CarreiraCareerIdPreparacaoRoute: CarreiraCareerIdPreparacaoRoute,
  CarreiraCareerIdPropostasRoute: CarreiraCareerIdPropostasRoute,
  CarreiraCareerIdSocialRoute: CarreiraCareerIdSocialRoute,
  CarreiraCareerIdTabelaRoute: CarreiraCareerIdTabelaRoute,
  CarreiraCareerIdIndexRoute: CarreiraCareerIdIndexRoute,
}

const CarreiraCareerIdRouteWithChildren =
  CarreiraCareerIdRoute._addFileChildren(CarreiraCareerIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarreirasRoute: CarreirasRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  CarreiraCareerIdRoute: CarreiraCareerIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
